### ISSUE TITLE
Losing text in the result 

### ISSUE THREAD

**Issue by Danielydsm** [prabhakar267/ocr-convert-image-to-text#35]
Hi, thank you for sharing your solution. 

I'm trying to convert scanned pdf to text. I used imagemagick to convert from pdf to jpg and OCR for the last conversion. I tried your code to see if I get better results but I still lose a lot of information in the process. Do you have any tips to improve my results? Or, is there a better way to look for standards in a document and I'm not seeing?

The document I try to check does not have a standard format. But usually the information I need are in a table

**Comment by avsaditya** [comment]
Would it be possible to post a sample pdf if it is not confidential.
I had the same problem sometime back.
The problem was with the resolution and dpi of the images.
You can save a high resolution image while extracting from pdf and use image (Pillow) library to enhance the dpi. Then the results might be satisfactory.
Hope it helps

**Comment by prabhakar267** [comment]
@Danielydsm There can be multiple reasons for a file to not be converted. If you can share a sample, it would be easier to pin-point exact reason. 
Meanwhile I'm closing the issue. Feel free to reopen if you'd like to share the file.
